on:
  push:
    branches: [experiment/windows-build]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: Windows Build (Experimental)
jobs:
    build:
        runs-on: windows-2025
        steps:
            - name: Setup MSYS2
              uses: msys2/setup-msys2@v2
              with:
                msystem: UCRT64
                release: false
                update: true
                install: |
                  base-devel
                  mingw-w64-ucrt-x86_64-binutils
                  mingw-w64-ucrt-x86_64-libadwaita
                  mingw-w64-ucrt-x86_64-gtk4
                  mingw-w64-ucrt-x86_64-gtksourceview5
                  mingw-w64-ucrt-x86_64-gobject-introspection
                  mingw-w64-ucrt-x86_64-vala
                  mingw-w64-ucrt-x86_64-granite7
                  mingw-w64-ucrt-x86_64-libsoup3
                  mingw-w64-ucrt-x86_64-libsecret
                  mingw-w64-ucrt-x86_64-desktop-file-utils
                  mingw-w64-ucrt-x86_64-meson
                  mingw-w64-ucrt-x86_64-ninja
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build and install custom libical with glib
              shell: msys2 {0}
              run: |
                cd build-windows/libical-with-glib
                makepkg-mingw --cleanbuild --syncdeps --force --noconfirm
                pacman -U *.pkg.tar.zst
            

